### ISSUE TITLE
Unable to use the standard

### ISSUE THREAD

**Issue by girishkc** [aik099/CodingStandard#103]
I am not able to use the standard. Keep getting the error message:
`phpcs: PHP Fatal error:  Uncaught Error: Class 'PHP_CodeSniffer_Exception' not found`

**Comment by aik099** [comment]
This coding standard can only be used with PHP_CodeSniffer 1.x/2.x version.

You're likely using latest PHP_CodeSniffer 3.x version where every class was renamed to make use of PHP namespaces. I'd like to update standard to 3.x version of PHP_CodeSniffer, but I'm short on time.

**Comment by girishkc** [comment]
Thanks for the quick replay. My apologies... I did not noticed it..

**Comment by aik099** [comment]
Actually I haven't written in docs about this. I'll update the README.
